### ISSUE TITLE
Feature Request: Network cycles code

### ISSUE THREAD

**Issue by ericmjl** [ericmjl/genotype-network#18]
Need to write function under genotype network class file that identifies network cycles.

**Comment by pharos916** [comment]
Here is the pseudocode I am thinking for this function:
def find_network_cycle(self, root):
    return nx.cycle_basis(self.G, root)

Where root specifies an (optional) node to search a cycle from. The documentation may be found here (https://networkx.github.io/documentation/latest/reference/generated/networkx.algorithms.cycles.cycle_basis.html).

The only problem is what data type the root would be. Is this a string that the user would input? Or would the node be an accession number? Or am I thinking too far ahead and it doesn't really matter? I'll proceed with implementation this weekend if I don't get an answer by then. 

Thanks,
Kyle

**Comment by ericmjl** [comment]
Sounds good. Give it a shot, and maybe quickly test the code  with the following set of nodes and edges:

```
G = nx.Graph()
G.add_edges_from([(1,2), (2,3), (3,1), (1,4), (2,5), (3,6)])
```

You might also want to try another toy graph that looks like this:

```
G.add_edges_from([(1,2), (2,3), (3,4), (4,5), (5,1), (1,3)])
```

The second example will see whether it will detect the "elementary" cycles (1, 2, 3) and (1, 3, 4, 5).

Finally, one last test to see if it will find cycles not joined by a path:

```
G.add_cycle([0, 1, 2, 3])
G.add_cycle([4, 5, 6, 7])
G.add_node(10)
```

If you can convince yourself that the output is correct, then go for it! :smile:

**Comment by ericmjl** [comment]
FWIW, `root` is an optional parameter. 

As for the data type, I think the logical choice is to use the amino acid sequence as the node in the graph definition, rather than accession number. After all, what's being passed into the genotype network constructor is a FASTA file of amino acid sequences, and it's easier to grab the node rather than node metadata when doing edge construction.
