### ISSUE TITLE
Necessity of list_processor, subgraph_processor, graph_combiner

### ISSUE THREAD

**Issue by pharos916** [ericmjl/genotype-network#19]
The way we set up the architecture of our software is meant to allow for multicore processing on the Koch cluster. Now that we know an analysis of 2500 genotypes takes less than an hour, we might not even need this functionality. We might have to rewrite much of our code, which might have to occur before adding the cycling finding functionality #18.

**Comment by ericmjl** [comment]
What needs to be re-written?

**Comment by ericmjl** [comment]
I have removed the files needed to do multi-core parallel processing.
