### ISSUE TITLE
Feature Request: Read gpickle function built within genotype network

### ISSUE THREAD

**Issue by pharos916** [ericmjl/genotype-network#20]
This would allow us to analyze previously built pickled networks using the genotype network api.

**Comment by pharos916** [comment]
Should we remove the gpickle and network cycles issues and add more, then?

**Comment by ericmjl** [comment]
Hmm... What do you mean?

**Comment by pharos916** [comment]
Since we added read gpickle and network cycles, do they still need to be issues on Github? 

And now that we've added the last two functions, what should we do moving forward?

**Comment by ericmjl** [comment]
I think it's worth testing the program on real dataset, but I'll also make a PyPI setup script first. Try it out on some contemporary H3s from the past year or two. If there are bugs that you find, post them as issues and let's take a look at them.

**Comment by pharos916** [comment]
There is already a sample dataset of contemporary H3s in the Test folder, named H3N8 HA 2013-2015.fasta.

However, I don't think we can make a genotype network, since I believe none of the sequences are only 1 amino acid apart (it would just be 20 nodes).

Should I edit the sequences to accordingly or add more sequences in the file? So far there are only 20.

**Comment by ericmjl** [comment]
What about contemporary H3N2s? That would be a relevant dataset to try out.

**Comment by ericmjl** [comment]
Btw, I have uploaded it to PyPI, so on Rous, you should be able to do a `pip install GenotypeNetwork`. The package description isn't complete yet, as I have yet to add a credit acknowledging your contributions, but at least stuff is out now.

**Comment by pharos916** [comment]
When I try to install the GenotypeNetwork package on Rous, I get this error
message. Does setup.py need to be debugged or is this a mistake on my part?

On Mon, Aug 3, 2015 at 5:13 PM, Eric Ma notifications@github.com wrote:

> Btw, I have uploaded it to PyPI, so on Rous, you should be able to do a pip
> install GenotypeNetwork. The package description isn't complete yet, as I
> have yet to add a credit acknowledging your contributions, but at least
> stuff is out now.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ericmjl/genotype-network/issues/20#issuecomment-127407667
> .

## 

Kyle Yuan
Department of Biological Engineering | Chemistry Minor
Massachusetts Institute of Technology | Class of 2016

**Comment by ericmjl** [comment]
What's the error message?

**Comment by pharos916** [comment]
I sent a picture in the last email. I reattached it here.

On Mon, Aug 3, 2015 at 6:54 PM, Eric Ma notifications@github.com wrote:

> Reopened #20 https://github.com/ericmjl/genotype-network/issues/20.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ericmjl/genotype-network/issues/20#event-372515695.

## 

Kyle Yuan
Department of Biological Engineering | Chemistry Minor
Massachusetts Institute of Technology | Class of 2016

**Comment by pharos916** [comment]
It says

Command "python setup.py egg_info" failed with error code 1 in
/tmp/pip-build-395x7x89/GenotypeNetwork

On Mon, Aug 3, 2015 at 7:06 PM, Kyle Yuan kyuan@mit.edu wrote:

> I sent a picture in the last email. I reattached it here.
> 
> On Mon, Aug 3, 2015 at 6:54 PM, Eric Ma notifications@github.com wrote:
> 
> > Reopened #20 https://github.com/ericmjl/genotype-network/issues/20.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/ericmjl/genotype-network/issues/20#event-372515695.
> 
> ## 
> 
> Kyle Yuan
> Department of Biological Engineering | Chemistry Minor
> Massachusetts Institute of Technology | Class of 2016

## 

Kyle Yuan
Department of Biological Engineering | Chemistry Minor
Massachusetts Institute of Technology | Class of 2016

**Comment by ericmjl** [comment]
I see. It may be an error with the setup.py script. Can you post this as an issue? I will get to it when I'm back at my computer.
