### ISSUE TITLE
setup.py for upload to PyPI and anaconda

### ISSUE THREAD

**Issue by ericmjl** [ericmjl/genotype-network#23]
I think we will need a setup.py script for uploading to PyPI and anaconda, so that others can begin to use the software package - yes, even before we write it up.

I will take care of this. Look out for some PRs coming over the week.

**Comment by ericmjl** [comment]
Setup script done. Next task, upload to PyPI and Binstar.

**Comment by pharos916** [comment]
Error when installed on Rous: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-395x7x89/GenotypeNetwork

See attached image.
![error_rous_080315](https://cloud.githubusercontent.com/assets/12633362/9050072/8f08c1c8-3a17-11e5-8575-e9b7125b9796.png)

**Comment by ericmjl** [comment]
Got it. Looks like the read me file isn't being uploaded with the rest of the package. I will get to it.

**Comment by ericmjl** [comment]
Okay, I think I've fixed it. Give it a shot, it works on Rous for me.
