### ISSUE TITLE
Add functionality to remove duplicate sequences

### ISSUE THREAD

**Issue by pharos916** [ericmjl/genotype-network#42]
For larger data sets, this could be helpful to reduce computation time. However, the same sequence might have different metadata, so we might have to choose which sequence to keep. What do you think about this, Eric?

**Comment by ericmjl** [comment]
Ah, this one - I have made a few PRs that implemented this. Specifically in here: https://github.com/ericmjl/genotype-network/blob/master/genotype_network/protein.py#L45

In this implementation, the amino acid sequence is stored as a node (string, not a Seq object or SeqRecord object), and the accession numbers are stored in the node metadata. The nodes are initialized first, and then the edges are drawn based on the single distance criteria.

**Comment by pharos916** [comment]
Oh, I see. With your implementation, there isn't any need to have an explicit check for duplicate sequences. You even have a line that computes computation time, which is great. Issue closed.

**Comment by ericmjl** [comment]
Love it, Kyle, you're getting good at this workflow :)
